name: argument
description: A new Flutter application.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: 1.1.1
  flutter_mobx: 1.1.0
  provider: ^4.1.2
  rxdart: 0.23.1
  flutter_launcher_icons: "^0.7.3"
  file_picker: ^1.9.0+1
  simple_animations: ^1.3.3
  flutter_bloc: ^4.0.0

  shared_preferences: 0.5.6+3

  flutter_masked_text: 0.8.0
  bot_toast: ^2.3.1
  intl: 0.16.1
  image_picker: ^0.6.6+4

  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: 1.9.0
  mobx_codegen: 1.0.3
  flutter_uploader: ^1.2.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  
