name: argument
description: A new Flutter application.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: 1.1.1
  flutter_mobx: 1.1.0
  provider: ^4.1.2
  rxdart: 0.23.1
  file_picker: ^1.9.0+1
  simple_animations: ^1.3.3
  flutter_bloc: ^4.0.0
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  folding_cell: "^0.1.2"
  modal_progress_hud: ^0.1.3
  dropdown_formfield: ^0.1.2
  google_fonts: ^1.1.0
  flare_flutter: ^2.0.5
  firebase_storage: 3.1.6

  shared_preferences: 0.5.6+3

  flutter_masked_text: 0.8.0
  bot_toast: ^2.3.1
  intl: 0.16.1
  image_picker: 0.6.7+2
  image_cropper: 1.2.3
  cached_network_image: 2.2.0+1
  sqflite:
  path:

  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: 1.9.0
  mobx_codegen: 1.0.3
  flutter_uploader: ^1.2.0
  flutter_launcher_icons: ^0.7.5


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/



scripts:
  mobx: flutter pub run build_runner build watch --delete-conflicting-outputs

  
